/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentOptionsRouteImport } from './routes/payment-options'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FindStoreRouteImport } from './routes/find-store'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOptionsRoute = PaymentOptionsRouteImport.update({
  id: '/payment-options',
  path: '/payment-options',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FindStoreRoute = FindStoreRouteImport.update({
  id: '/find-store',
  path: '/find-store',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/find-store': typeof FindStoreRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRouteWithChildren
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment-options': typeof PaymentOptionsRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/login/$': typeof LoginSplatRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/find-store': typeof FindStoreRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRouteWithChildren
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment-options': typeof PaymentOptionsRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/login/$': typeof LoginSplatRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/find-store': typeof FindStoreRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRouteWithChildren
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment-options': typeof PaymentOptionsRoute
  '/profile': typeof ProfileRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sustainability': typeof SustainabilityRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/login/$': typeof LoginSplatRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/feedback'
    | '/find-store'
    | '/investors'
    | '/login'
    | '/new-arrivals'
    | '/news'
    | '/newsletter'
    | '/order-success'
    | '/payment-options'
    | '/profile'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/shop'
    | '/sustainability'
    | '/wishlist'
    | '/category/$slug'
    | '/login/$'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/feedback'
    | '/find-store'
    | '/investors'
    | '/login'
    | '/new-arrivals'
    | '/news'
    | '/newsletter'
    | '/order-success'
    | '/payment-options'
    | '/profile'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/shop'
    | '/sustainability'
    | '/wishlist'
    | '/category/$slug'
    | '/login/$'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/feedback'
    | '/find-store'
    | '/investors'
    | '/login'
    | '/new-arrivals'
    | '/news'
    | '/newsletter'
    | '/order-success'
    | '/payment-options'
    | '/profile'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/shop'
    | '/sustainability'
    | '/wishlist'
    | '/category/$slug'
    | '/login/$'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  FindStoreRoute: typeof FindStoreRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRouteWithChildren
  NewArrivalsRoute: typeof NewArrivalsRoute
  NewsRoute: typeof NewsRoute
  NewsletterRoute: typeof NewsletterRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PaymentOptionsRoute: typeof PaymentOptionsRoute
  ProfileRoute: typeof ProfileRoute
  ReturnsRoute: typeof ReturnsRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SustainabilityRoute: typeof SustainabilityRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-options': {
      id: '/payment-options'
      path: '/payment-options'
      fullPath: '/payment-options'
      preLoaderRoute: typeof PaymentOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-store': {
      id: '/find-store'
      path: '/find-store'
      fullPath: '/find-store'
      preLoaderRoute: typeof FindStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  FindStoreRoute: FindStoreRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRouteWithChildren,
  NewArrivalsRoute: NewArrivalsRoute,
  NewsRoute: NewsRoute,
  NewsletterRoute: NewsletterRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PaymentOptionsRoute: PaymentOptionsRoute,
  ProfileRoute: ProfileRoute,
  ReturnsRoute: ReturnsRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SustainabilityRoute: SustainabilityRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
